"""initial

Revision ID: 3a0891969810
Revises:
Create Date: 2023-08-02 16:58:22.812306

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3a0891969810"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Text(), nullable=False),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("image", sa.BLOB(), nullable=False),
        sa.Column("file_id", sa.Text(), nullable=True),
        sa.Column("date", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu_texts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("day"),
    )
    op.create_table(
        "settings",
        sa.Column("first_date", sa.Text(), nullable=False),
        sa.Column("days_count", sa.Integer(), nullable=False),
        sa.Column("owner", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    op.drop_table("menu_texts")
    op.drop_table("menu")
    op.drop_table("dates")
    op.drop_table("admins")
    # ### end Alembic commands ###
